### ISSUE TITLE
[INCIDENT][MOC/Zero] - OCS storage cluster full

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#312]
The OCS storage cluster filled up yesterday evening. This has disabled write access to the cluster, resulting in a number of problems.

Alerts:

- https://github.com/operate-first/alerts/issues/6824

Support requests:

- https://github.com/operate-first/support/issues/243

**Comment by larsks** [comment]
We are following this procedure to re-enable write access to the cluser:

https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/4/html-single/troubleshooting_guide/index#deleting-data-from-a-full-storage-cluster_diag

**Comment by larsks** [comment]
In order to free up space on the cluster, we're going to relocate the image-registry pv (200GB) onto NFS storage.

**Comment by tumido** [comment]
Mitigation ideas to the future (include in post-mortem):
- Use Noobaa storage class only: https://github.com/operate-first/SRE/issues/313
- Make quotas on object buckets possible: https://github.com/rook/rook/issues/7906

**Comment by HumairAK** [comment]
Update: we're noticing a large sum of data being used by rgw buckets we're working on moving these and/or clearing them up where possible.

**Comment by HumairAK** [comment]
We have identified thanos as the culprit that's using up most of the space, ~800Gib replicated thrice. 

We are investigating setting up a minio server that leverages the nfs storage and transferring the data there, to what we expect will be manually allocated buckets.

**Comment by HumairAK** [comment]
The pools for reference: 

```
POOLS:
    POOL                                                      ID     STORED      OBJECTS     USED        %USED     MAX AVAIL
    .rgw.root                                                  1     4.7 KiB          16     2.8 MiB         0       303 GiB
    ocs-storagecluster-cephblockpool                           2     2.0 GiB         573     6.0 GiB      0.66       303 GiB
    ocs-storagecluster-cephobjectstore.rgw.control             3         0 B           8         0 B         0       303 GiB
    ocs-storagecluster-cephfilesystem-metadata                 4     711 MiB     177.41k     1.1 GiB      0.13       303 GiB
    ocs-storagecluster-cephfilesystem-data0                    5     278 GiB     852.99k     960 GiB     51.37       303 GiB
    ocs-storagecluster-cephobjectstore.rgw.meta                6      19 KiB          87      12 MiB         0       303 GiB
    ocs-storagecluster-cephobjectstore.rgw.log                 7     9.6 MiB         229      26 MiB         0       303 GiB
    ocs-storagecluster-cephobjectstore.rgw.buckets.index       8      53 MiB         176      53 MiB         0       303 GiB
    ocs-storagecluster-cephobjectstore.rgw.buckets.non-ec      9        27 B           1     192 KiB         0       303 GiB
    ocs-storagecluster-cephobjectstore.rgw.buckets.data       10     888 GiB     393.80k     2.6 TiB     74.72       303 GiB
```

Here thanos is using an rgw bucket, and is the highest consumer of storage in `ocs-storagecluster-cephobjectstore.rgw.buckets.data` this was found out by manually running s3 cli commands on each rgw bucket (of which there are ~5)

**Comment by HumairAK** [comment]
We are also considering reducing the number of replicas, from the ceph irc channel we got one person confirming that the cluster should rebalance if we do this.

**Comment by larsks** [comment]
We have set `size=2` for the `ocs-storagecluster-cephobjectstore.rgw.buckets.data`. This triggers rebalancing for the pool, so that's immediately freed up space; we've gone from:

```
RAW STORAGE:
    CLASS     SIZE        AVAIL       USED        RAW USED     %RAW USED
    hdd       4.9 TiB     1.3 TiB     3.6 TiB      3.6 TiB         73.08
    TOTAL     4.9 TiB     1.3 TiB     3.6 TiB      3.6 TiB         73.08

POOLS:
    POOL                                                      ID     STORED      OBJECTS     USED        %USED     MAX AVAIL
    .rgw.root                                                  1     4.7 KiB          16     2.8 MiB         0       303 GiB
    ocs-storagecluster-cephblockpool                           2     2.0 GiB         573     6.0 GiB      0.66       303 GiB
    ocs-storagecluster-cephobjectstore.rgw.control             3         0 B           8         0 B         0       303 GiB
    ocs-storagecluster-cephfilesystem-metadata                 4     711 MiB     177.41k     1.1 GiB      0.13       303 GiB
    ocs-storagecluster-cephfilesystem-data0                    5     278 GiB     852.99k     960 GiB     51.37       303 GiB
    ocs-storagecluster-cephobjectstore.rgw.meta                6      19 KiB          87      12 MiB         0       303 GiB
    ocs-storagecluster-cephobjectstore.rgw.log                 7     9.6 MiB         229      26 MiB         0       303 GiB
    ocs-storagecluster-cephobjectstore.rgw.buckets.index       8      53 MiB         176      53 MiB         0       303 GiB
    ocs-storagecluster-cephobjectstore.rgw.buckets.non-ec      9        27 B           1     192 KiB         0       303 GiB
    ocs-storagecluster-cephobjectstore.rgw.buckets.data       10     888 GiB     393.80k     2.6 TiB     74.72       303 GiB
```

To:

```
RAW STORAGE:
    CLASS     SIZE        AVAIL       USED        RAW USED     %RAW USED
    hdd       4.9 TiB     1.9 TiB     3.0 TiB      3.0 TiB         61.83
    TOTAL     4.9 TiB     1.9 TiB     3.0 TiB      3.0 TiB         61.83

POOLS:
    POOL                                                      ID     STORED      OBJECTS     USED        %USED     MAX AVAIL
    .rgw.root                                                  1     4.7 KiB          16     2.8 MiB         0       478 GiB
    ocs-storagecluster-cephblockpool                           2     2.0 GiB         573     6.0 GiB      0.42       478 GiB
    ocs-storagecluster-cephobjectstore.rgw.control             3         0 B           8         0 B         0       478 GiB
    ocs-storagecluster-cephfilesystem-metadata                 4     734 MiB     177.46k     1.2 GiB      0.08       478 GiB
    ocs-storagecluster-cephfilesystem-data0                    5     281 GiB     853.68k     968 GiB     40.30       478 GiB
    ocs-storagecluster-cephobjectstore.rgw.meta                6      19 KiB          87      12 MiB         0       478 GiB
    ocs-storagecluster-cephobjectstore.rgw.log                 7     9.6 MiB         229      26 MiB         0       478 GiB
    ocs-storagecluster-cephobjectstore.rgw.buckets.index       8      53 MiB         176      53 MiB         0       478 GiB
    ocs-storagecluster-cephobjectstore.rgw.buckets.non-ec      9        54 B           2     384 KiB         0       478 GiB
    ocs-storagecluster-cephobjectstore.rgw.buckets.data       10     1.0 TiB     394.44k     2.1 TiB     59.56       717 GiB
```

And `RAW USED` is still dropping.

**Comment by larsks** [comment]
We have set the default storageclass to moc-nfs-csi in https://github.com/operate-first/apps/pull/652

**Comment by larsks** [comment]
The ceph cluster is now `HEALTH_OK`.

```
  cluster:
    id:     895c1f68-fc4c-4355-a7bf-51c57c78d59b
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum e,f,g (age 2w)
    mgr: a(active, since 2w)
    mds: ocs-storagecluster-cephfilesystem:1 {0=ocs-storagecluster-cephfilesystem-b=up:active} 1 up:standby-replay
    osd: 9 osds: 9 up (since 6d), 9 in (since 2w); 7 remapped pgs
    rgw: 2 daemons active (ocs.storagecluster.cephobjectstore.a, ocs.storagecluster.cephobjectstore.b)

  task status:
    scrub status:
        mds.ocs-storagecluster-cephfilesystem-a: idle
        mds.ocs-storagecluster-cephfilesystem-b: idle

  data:
    pools:   10 pools, 464 pgs
    objects: 1.43M objects, 1.1 TiB
    usage:   2.8 TiB used, 2.1 TiB / 4.9 TiB avail
    pgs:     16612/3885162 objects misplaced (0.428%)
             457 active+clean
             5   active+remapped+backfill_wait
             2   active+remapped+backfilling

  io:
    client:   61 MiB/s rd, 7.0 MiB/s wr, 117 op/s rd, 40 op/s wr
    recovery: 17 MiB/s, 7 objects/s

```

**Comment by HumairAK** [comment]
This incident has been resolved.
Please let us know if you continue to see any remaining issues. We will be following up with a post-mortem in this thread.

**Comment by larsks** [comment]
I have reset `full_ratio` back to the default value of `0.95`.

**Comment by tumido** [comment]
We still have some fall off from this in the cluster:
```
$ oc get -A objectbucketclaims

NAMESPACE           NAME                            STORAGE-CLASS                 PHASE     AGE
ds-black-flake      backup-black-flake              openshift-storage.noobaa.io   Bound     52d
ds-black-flake      black-flake                     openshift-storage.noobaa.io   Bound     52d
opf-argo            mailing-list-analysis-toolkit   openshift-storage.noobaa.io   Bound     61d
opf-ci-prow         ci-prow-artifacts               ocs-storagecluster-ceph-rgw   Bound     68d
opf-ci-prow         ci-prow-artifacts-s3            openshift-storage.noobaa.io             2d20h
opf-datacatalog     opf-datacatalog-bucket          openshift-storage.noobaa.io   Bound     65d
opf-datacatalog     test-public-bucket              openshift-storage.noobaa.io   Bound     46d
opf-datacatalog     user-bucket-dtuchyna            openshift-storage.noobaa.io   Bound     65d
opf-observatorium   loki-objectstorage              ocs-storagecluster-ceph-rgw   Bound     68d
opf-observatorium   loki-objectstorage-backup       openshift-storage.noobaa.io   Pending   2d23h
opf-observatorium   thanos-objectstorage            ocs-storagecluster-ceph-rgw   Bound     66d
thoth-graph-prod    thoth-zero-ceph                 openshift-storage.noobaa.io   Bound     60d
```

`ci-prow-artifacts-s3` bucket is `Lost`.
`loki-objectstorage-backup` is `Pending` indefinitely.

**Comment by HumairAK** [comment]
> ci-prow-artifacts-s3 bucket is Lost. 

Is this related to CI being broken? @harshad16

**Comment by harshad16** [comment]
still working on the migration of ci-prow s3 
opf-ci-prow         ci-prow-artifacts               ocs-storagecluster-ceph-rgw   Bound     68d
opf-ci-prow         ci-prow-artifacts-s3 

`ci-prow-artifacts-s3 bucket is Lost.`
saw this , don't know what that means. Can someone shed light on this?
